---
  - name: Install required Python libraries
    pip:
      name: ["flask", "flask-mysql"]
      state: present
      executable: pip3.6
    tags:
      - install_req

  - name: Copy source code
    copy:
      src: /Users/nagbhat/Desktop/dev/ansible/app.py
      dest: /opt/app.py

  - name: Start web server
    shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
